snapshot: lts-24.35

packages:
- .

extra-deps:
- Cabal-3.16.1.0
- Cabal-syntax-3.16.1.0
- tar-0.7.2.0
- rel8-1.7.0.0
- ../hackage-server-v3/hackage-api
- github: tweag/ede
  commit: 70d34146d01a3766f2aef1a580e4224238ed6f90
- github: alpmestan/servant-ede
  commit: 173fecca9078bc2e81ff4d6244f08b15d70f81b5
- github: haskell-servant/servant
  commit: 866e272feb42411aa208f21898c190f1c117780d
  subdir: servant

nix:
  packages:
    - gd
    - libpng
    - libz
    - libjpeg
    - fontconfig
    - expat
    - postgresql
    - pkg-config
    - openssl

allow-newer: true

