snapshot: lts-24.35

packages:
- .

extra-deps:
- Cabal-3.16.1.0
- Cabal-syntax-3.16.1.0
- tar-0.7.0.0
- rel8-1.7.0.0

nix:
  packages:
    - gd
    - libpng
    - libz
    - libjpeg
    - fontconfig
    - expat
    - postgresql
    - pkg-config
    - openssl

allow-newer: true

